In [20]:
import jax.numpy as np
from jax import grad, vmap, hessian
from jax import random 

def example(x):
    f=x**2 
    return f

key = random.PRNGKey(0)
batch_size=5
d=1
X_t=random.normal(key, (batch_size, 1))


f=example
df=vmap(grad(f))
#ddf=vmap(hessian(f))
df_t=df(X_t)

TypeError: Gradient only defined for scalar-output functions. Output had shape: (1,).

In [16]:
X_t.shape

(5, 1)

In [9]:
X_t

Array([[-0.3721109 ,  0.26423115],
       [-0.18252768, -0.7368197 ],
       [-0.44030377, -0.1521442 ],
       [-0.67135346, -0.5908641 ],
       [ 0.73168886,  0.5673026 ]], dtype=float32)

In [6]:
f(X_t)

Array([0.17178288, 0.6127213 ], dtype=float32)

In [4]:
df_t

Array([[-0.7442218 ,  0.5284623 ],
       [-0.36505535, -1.4736394 ],
       [-0.88060755, -0.3042884 ],
       [-1.3427069 , -1.1817282 ],
       [ 1.4633777 ,  1.1346052 ]], dtype=float32)

In [5]:
ddf_t=ddf(X_t)
ddf_t

Array([[[2., 0.],
        [0., 2.]],

       [[2., 0.],
        [0., 2.]],

       [[2., 0.],
        [0., 2.]],

       [[2., 0.],
        [0., 2.]],

       [[2., 0.],
        [0., 2.]]], dtype=float32)